name: .NET Test

# Run the build on push and pull requests.
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository.
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    # Set up .NET 9.0.
    - name: Set Up .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    # Run the .NET unit tests.
    - name: Run .NET Tests
      run: dotnet test